module.exports = [
  { source: "[偷笑]", show: "n(681)" },
  { source: "[愉快]", show: "n(682)" },
  { source: "[灵光一现]", show: "n(686)" },
  { source: "[憨笑]", show: "n(688)" },
  { source: "[奋斗]", show: "n(690)" },
  { source: "[赞]", show: "n(769)" },
  { source: "[握手]", show: "n(771)" },
  { source: "[比心]", show: "n(774)" },
  { source: "[击掌]", show: "n(776)" },
  { source: "[胜利]", show: "n(780)" },
  { source: "[抱拳]", show: "n(781)" },
  { source: "[666]", show: "n(789)" },
  { source: "[给力]", show: "n(790)" },
  { source: "[v5]", show: "n(791)" },
];
